document.write("<div id=सर्वार्थसिद्धि class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkGreen>﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>﻿तन्निसर्गादधिगमाद्वा॥३॥</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>﻿जीवजीवास्रवबन्धसंवरनिर्जरामोक्षास्तत्त्वम्॥४॥</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿नामस्थापनाद्रव्यभाव तस्तन्न्यासः॥५॥</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿प्रमाणनयैरधिगमः॥६॥</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>﻿निर्देशस्वामित्वसाधनाधिकरणस्थितिविधानतः॥७॥</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkGreen>﻿तत्प्रमाणे॥१०॥</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkBlue>﻿आद्ये परोक्षम्॥११॥</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkGreen>﻿प्रत्यक्षमन्यत्॥१२॥</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkBlue>﻿मतिः स्मृतिः संज्ञा चिन्ताsभिनिबोध इत्यानर्थान्तरम्॥१३॥</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkGreen>﻿तदिन्द्रयानिन्द्रिय निमित्तम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkBlue>﻿अवग्रहेहावाय धारणाः॥१५॥</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkGreen>﻿बहुबहुविधक्षिप्रानिःसृतानुक्तध्रुवाणां सेतराणाम्‌॥१६॥</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkBlue>﻿अर्थस्य॥१७॥</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkGreen>﻿व्यञ्जनस्यावग्रहः॥१८॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>﻿न चक्षुरनिन्द्रियाभ्याम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkBlue>﻿भवप्रत्ययोऽवधिर्देवनारकाणाम्॥२१॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>﻿क्षयोपशमनिमित्तः षड्विकल्पः शेषाणाम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkBlue>﻿ऋजुविपुलमती मनःपर्ययः॥२३॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>﻿विशुद्धयप्रतिपाताभ्यां तद्विशेषः॥२४॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>﻿विशुद्धिक्षेत्रस्वामिविषयेभ्योऽवधिमनःपर्यययोः॥२५॥</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkGreen>﻿मतिश्रुतयोर्निबन्धो द्रव्येष्वसर्वपर्यायेषु॥२६॥</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkBlue>﻿रूपिष्ववधेः॥२७॥</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkGreen>﻿तदनन्तभागे मनःपर्ययस्य॥२८॥</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkBlue>﻿सर्वद्रव्यपर्यायेषु केवलस्य॥२९॥</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkGreen>﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkBlue>﻿मतिश्रुतावधयो विपर्ययश्‍च॥३१॥</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkGreen>﻿सदसतोरविशेषाद्यदृच्छोपलब्धेरुन्मत्तवत्॥३२॥</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkBlue>﻿नैगमसंग्रहव्यवहारर्जुसूत्रशब्दसमभिरूढैवंभूता नयाः॥३३॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=राजवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkGreen>﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkBlue>﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿प्रमाणनयैरधिगमः॥६॥</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkBlue>﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkGreen>﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkBlue>﻿प्रत्यक्षमन्यत्॥१२॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkBlue>﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=तत्त्वार्थमंजुषा class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='00_मंगलाचरण.html'><font size=4>00_मंगलाचरण</font></a></li>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkGreen>﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>﻿तन्निसर्गादधिगमाद्वा॥३॥</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>﻿जीवजीवास्रवबन्धसंवरनिर्जरामोक्षास्तत्त्वम्॥४॥</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿नामस्थापनाद्रव्यभाव तस्तन्न्यासः॥५॥</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿प्रमाणनयैरधिगमः॥६॥</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>﻿निर्देशस्वामित्वसाधनाधिकरणस्थितिविधानतः॥७॥</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkGreen>﻿तत्प्रमाणे॥१०॥</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkBlue>﻿आद्ये परोक्षम्॥११॥</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkGreen>﻿प्रत्यक्षमन्यत्॥१२॥</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkBlue>﻿मतिः स्मृतिः संज्ञा चिन्ताsभिनिबोध इत्यानर्थान्तरम्॥१३॥</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkGreen>﻿तदिन्द्रयानिन्द्रिय निमित्तम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkBlue>﻿अवग्रहेहावाय धारणाः॥१५॥</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkGreen>﻿बहुबहुविधक्षिप्रानिःसृतानुक्तध्रुवाणां सेतराणाम्‌॥१६॥</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkBlue>﻿अर्थस्य॥१७॥</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkGreen>﻿व्यञ्जनस्यावग्रहः॥१८॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>﻿न चक्षुरनिन्द्रियाभ्याम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkBlue>﻿भवप्रत्ययोऽवधिर्देवनारकाणाम्॥२१॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>﻿क्षयोपशमनिमित्तः षड्विकल्पः शेषाणाम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkBlue>﻿ऋजुविपुलमती मनःपर्ययः॥२३॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>﻿विशुद्धयप्रतिपाताभ्यां तद्विशेषः॥२४॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>﻿विशुद्धिक्षेत्रस्वामिविषयेभ्योऽवधिमनःपर्यययोः॥२५॥</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkGreen>﻿मतिश्रुतयोर्निबन्धो द्रव्येष्वसर्वपर्यायेषु॥२६॥</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkBlue>﻿रूपिष्ववधेः॥२७॥</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkGreen>﻿तदनन्तभागे मनःपर्ययस्य॥२८॥</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkBlue>﻿सर्वद्रव्यपर्यायेषु केवलस्य॥२९॥</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkGreen>﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkBlue>﻿मतिश्रुतावधयो विपर्ययश्‍च॥३१॥</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkGreen>﻿सदसतोरविशेषाद्यदृच्छोपलब्धेरुन्मत्तवत्॥३२॥</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkBlue>﻿नैगमसंग्रहव्यवहारर्जुसूत्रशब्दसमभिरूढैवंभूता नयाः॥३३॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=कैलाशचंदजी_शास्त्री class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='00.html'><font size=4><font color=darkPurple><b>00</b></font> - <font color=darkGreen>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkGreen>﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>﻿तन्निसर्गादधिगमाद्वा॥३॥</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>﻿जीवजीवास्रवबन्धसंवरनिर्जरामोक्षास्तत्त्वम्॥४॥</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿नामस्थापनाद्रव्यभाव तस्तन्न्यासः॥५॥</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿प्रमाणनयैरधिगमः॥६॥</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>﻿निर्देशस्वामित्वसाधनाधिकरणस्थितिविधानतः॥७॥</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkGreen>﻿तत्प्रमाणे॥१०॥</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkBlue>﻿आद्ये परोक्षम्॥११॥</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkGreen>﻿प्रत्यक्षमन्यत्॥१२॥</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkBlue>﻿मतिः स्मृतिः संज्ञा चिन्ताsभिनिबोध इत्यानर्थान्तरम्॥१३॥</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkGreen>﻿तदिन्द्रयानिन्द्रिय निमित्तम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkBlue>﻿अवग्रहेहावाय धारणाः॥१५॥</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkGreen>﻿बहुबहुविधक्षिप्रानिःसृतानुक्तध्रुवाणां सेतराणाम्‌॥१६॥</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkBlue>﻿अर्थस्य॥१७॥</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkGreen>﻿व्यञ्जनस्यावग्रहः॥१८॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>﻿न चक्षुरनिन्द्रियाभ्याम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkBlue>﻿भवप्रत्ययोऽवधिर्देवनारकाणाम्॥२१॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>﻿क्षयोपशमनिमित्तः षड्विकल्पः शेषाणाम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkBlue>﻿ऋजुविपुलमती मनःपर्ययः॥२३॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>﻿विशुद्धयप्रतिपाताभ्यां तद्विशेषः॥२४॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>﻿विशुद्धिक्षेत्रस्वामिविषयेभ्योऽवधिमनःपर्यययोः॥२५॥</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkGreen>﻿मतिश्रुतयोर्निबन्धो द्रव्येष्वसर्वपर्यायेषु॥२६॥</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkBlue>﻿रूपिष्ववधेः॥२७॥</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkGreen>﻿तदनन्तभागे मनःपर्ययस्य॥२८॥</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkBlue>﻿सर्वद्रव्यपर्यायेषु केवलस्य॥२९॥</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkGreen>﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkBlue>﻿मतिश्रुतावधयो विपर्ययश्‍च॥३१॥</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkGreen>﻿सदसतोरविशेषाद्यदृच्छोपलब्धेरुन्मत्तवत्॥३२॥</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkBlue>﻿नैगमसंग्रहव्यवहारर्जुसूत्रशब्दसमभिरूढैवंभूता नयाः॥३३॥</font></font></a></li>");
document.write("</ul></div>");
