document.write("<div id=सर्वार्थसिद्धि class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4>01</font></a></li>");
document.write("        <li><a href='02.html'><font size=4>02</font></a></li>");
document.write("        <li><a href='03.html'><font size=4>03</font></a></li>");
document.write("        <li><a href='04.html'><font size=4>04</font></a></li>");
document.write("        <li><a href='05.html'><font size=4>05</font></a></li>");
document.write("        <li><a href='06.html'><font size=4>06</font></a></li>");
document.write("        <li><a href='07.html'><font size=4>07</font></a></li>");
document.write("        <li><a href='08.html'><font size=4>08</font></a></li>");
document.write("        <li><a href='09.html'><font size=4>09</font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("        <li><a href='10.html'><font size=4>10</font></a></li>");
document.write("        <li><a href='11.html'><font size=4>11</font></a></li>");
document.write("        <li><a href='12.html'><font size=4>12</font></a></li>");
document.write("        <li><a href='13.html'><font size=4>13</font></a></li>");
document.write("        <li><a href='14.html'><font size=4>14</font></a></li>");
document.write("        <li><a href='15.html'><font size=4>15</font></a></li>");
document.write("        <li><a href='16.html'><font size=4>16</font></a></li>");
document.write("        <li><a href='17.html'><font size=4>17</font></a></li>");
document.write("        <li><a href='18.html'><font size=4>18</font></a></li>");
document.write("        <li><a href='19.html'><font size=4>19</font></a></li>");
document.write("        <li><a href='20.html'><font size=4>20</font></a></li>");
document.write("        <li><a href='21.html'><font size=4>21</font></a></li>");
document.write("        <li><a href='22.html'><font size=4>22</font></a></li>");
document.write("        <li><a href='23.html'><font size=4>23</font></a></li>");
document.write("        <li><a href='24.html'><font size=4>24</font></a></li>");
document.write("        <li><a href='25.html'><font size=4>25</font></a></li>");
document.write("        <li><a href='26.html'><font size=4>26</font></a></li>");
document.write("        <li><a href='27.html'><font size=4>27</font></a></li>");
document.write("</ul></div>");
document.write("<div id=राजवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='24.html'><font size=4>24</font></a></li>");
document.write("</ul></div>");
