document.write("<div id=सर्वार्थसिद्धि class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿काय-वाङ्मन: कर्म-योग: ॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkGreen>﻿स आस्रव: ॥२॥</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>﻿शुभ: पुण्यस्याशुभ: पापस्य ॥३॥</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>﻿सकषायाकषाययो: साम्परायिकेर्यापथयो: ॥४॥</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿इन्द्रिय-कषायाव्रत-क्रिया: पंच-चतु:-पंच-पंचविंशति-संख्या: पूर्वस्य भेदा: ॥५॥</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿तीव्र-मंद-ज्ञाताज्ञात-भावाधिकरण-वीर्य-विशेषेभ्यस्तद्विशेष: ॥६॥</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>﻿अधिकरणं जीवाजीवा: ॥७॥</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>﻿आद्यं संरम्भ-समारम्भारम्भयोग कृत-कारितानुमत-कषाय-विशेषैस्त्रिस्त्रिस्त्रि-श्चतुश्चैकश: ॥८॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>निर्वर्तना-निक्षेप-संयोग-निसर्गा द्विचतुद्र्वि-त्रिभेदा: परम्॥९॥</font></font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkBlue>तत्प्रदोष-निन्हव-मात्सर्यान्तरायासादनोपघाता ज्ञान-दर्शनावरणयो:॥१०॥</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkGreen>दु:ख-शोक-तापाक्रन्दन-वध-परिदेवनान्यात्म-परोभय-स्थानान्यसद्वेद्यस्य॥११॥</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkBlue>भूत-व्रत्यनुकम्पादान-सराग-संयमादि-योग: क्षांति: शौचमिति सद्वेद्यस्य॥१२॥</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkGreen>केवलि-श्रुत-संघ-धर्मदेवावर्णवादो दर्शनमोहस्य॥१३॥</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkBlue>कषायोदयात्तीव्र-परिणामश्चारित्र-मोहस्य॥१४॥</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkGreen>बह्वारम्भ-परिग्रहत्वं नारकस्यायुष:॥१५॥</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkBlue>माया तैर्यग्योनस्य॥१६॥</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkGreen>अल्पारम्भ परिग्रहत्वं मानुषस्य॥१७॥</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkBlue>स्वभाव-मार्दवं च॥१८॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkGreen>नि:शील-व्रतित्वं च सर्वेषाम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkBlue>सरागसंयम-संयमा-संयमाकामनिर्जराबालतपांसि देवस्य॥२०॥</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkGreen>सम्यक्त्वं च॥२१॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkBlue>योगवक्रता विसंवादनं चाशुभस्य नाम्न:॥२२॥</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkGreen>तद्विपरीतं शुभस्य॥२३॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkBlue>दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य॥२४॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkGreen>परात्म-निन्दा-प्रशंसे सदसद्गुणोच्छादनोद्भावने च नीचैर्गोत्रस्य॥२५॥</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkBlue>तद्विपर्ययो नीचैर्वृत्त्यनुत्सेकौ चोत्तरस्य॥२६॥</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkGreen>विघ्नकरण-मन्तरायस्य॥२७॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=राजवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkBlue>﻿स आस्रव: ॥२॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य॥२४॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=श्लोकवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿इन्द्रिय-कषायाव्रत-क्रिया: पंच-चतु:-पंच-पंचविंशति-संख्या: पूर्वस्य भेदा: ॥५॥</font></font></a></li>");
document.write("</ul></div>");
