document.write("<div id=पं-जचंदजी-छाबडा class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01-02.html'><font size=4>01-02</font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkGreen>﻿सम्यग्दर्शनादि तीन भावों का स्वरूप</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkBlue>﻿जो तीन भाव जीव के हैं उनकी शुद्धता के लिए चारित्र दो प्रकार का कहा है</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkGreen>﻿दो प्रकार का चारित्र</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkBlue>﻿सम्यक्त्वचरण चारित्र के मल दोषों का परिहार</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkGreen>﻿ सम्यक्त्व के आठ अंग</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkBlue>﻿इसप्रकार पहिला सम्यक्त्वाचरण चारित्र कहा</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkGreen>﻿सम्यक्त्वाचरण चारित्र को अंगीकार करके संयमचरण चारित्र को अंगीकार करने की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkBlue>﻿सम्यक्त्वाचरण से भ्रष्ट और वे संयमाचरण सहित को मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='11-12.html'><font size=4>11-12</font></a></li>");
document.write("        <li><a href='11.html'><font size=4>11</font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkGreen>﻿सम्यक्त्व कैसे छूटता है?</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkBlue>﻿सम्यक्त्व से च्युत कब नहीं होता है?</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkGreen>﻿अज्ञान मिथ्यात्व कुचारित्र के त्याग का उपदेश</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkBlue>﻿फिर उपदेश करते हैं</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkGreen>﻿यह जीव अज्ञान और मिथ्यात्व के दोष से मिथ्यामार्ग में प्रवर्तन करता है</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन-ज्ञान-श्रद्धान से चारित्र के दोष दूर होते हैं</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन-ज्ञान-चारित्र से शीघ्र मोक्ष</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkBlue>﻿सम्यक्त्वाचरण चारित्र के कथन का संकोच करते हैं</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkGreen>﻿संयमाचरण चारित्र</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkBlue>﻿सागार संयमाचरण</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkGreen>﻿इन स्थानों में संयम का आचरण किसप्रकार से है?</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkBlue>﻿पाँच अणुव्रतों का स्वरूप</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkGreen>﻿तीन गुणव्रत</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkBlue>﻿चार शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkGreen>﻿यतिधर्म </font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkBlue>﻿यतिधर्म की सामग्री</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkGreen>﻿पाँच इन्द्रियों के संवरण का स्वरूप</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4>30</font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkGreen>﻿इनको महाव्रत क्यों कहते हैं?</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkBlue>﻿अहिंसाव्रत की पाँच भावना</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkGreen>﻿सत्य महाव्रत की भावना</font></font></a></li>");
document.write("        <li><a href='34.html'><font size=4><font color=darkPurple><b>34</b></font> - <font color=darkBlue>﻿अचौर्य महाव्रत की भावना </font></font></a></li>");
document.write("        <li><a href='35.html'><font size=4><font color=darkPurple><b>35</b></font> - <font color=darkGreen>﻿ब्रह्मचर्य महाव्रत की भावना</font></font></a></li>");
document.write("        <li><a href='36.html'><font size=4><font color=darkPurple><b>36</b></font> - <font color=darkBlue>﻿पाँच अपरिग्रह महाव्रत की भावना</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4><font color=darkPurple><b>37</b></font> - <font color=darkGreen>﻿पाँच समिति</font></font></a></li>");
document.write("        <li><a href='38.html'><font size=4><font color=darkPurple><b>38</b></font> - <font color=darkBlue>﻿ज्ञान का स्वरूप</font></font></a></li>");
document.write("        <li><a href='39.html'><font size=4><font color=darkPurple><b>39</b></font> - <font color=darkGreen>﻿जो इसप्रकार ज्ञान से ऐसे जानता है, वह सम्यग्ज्ञानी</font></font></a></li>");
document.write("        <li><a href='40.html'><font size=4><font color=darkPurple><b>40</b></font> - <font color=darkBlue>﻿मोक्षमार्ग को जानकर श्रद्धा सहित इसमें प्रवृत्ति करता है, वह शीघ्र ही मोक्ष को प्राप्त करता है</font></font></a></li>");
document.write("        <li><a href='41.html'><font size=4><font color=darkPurple><b>41</b></font> - <font color=darkGreen>﻿निश्चयचारित्ररूप ज्ञान का स्वरूप कि महिमा</font></font></a></li>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkBlue>﻿गुण दोष को जानने के लिए ज्ञान को भले प्रकार से जानना</font></font></a></li>");
document.write("        <li><a href='43.html'><font size=4><font color=darkPurple><b>43</b></font> - <font color=darkGreen>﻿जो सम्यग्ज्ञान सहित चारित्र धारण करता है, वह थोड़े ही काल में अनुपम सुख को पाता है</font></font></a></li>");
document.write("        <li><a href='44.html'><font size=4><font color=darkPurple><b>44</b></font> - <font color=darkBlue>﻿चारित्र के कथन का संकोच</font></font></a></li>");
document.write("        <li><a href='45.html'><font size=4><font color=darkPurple><b>45</b></font> - <font color=darkGreen>﻿चारित्रपाहुड़ को भाने का उपदेश और इसका फल </font></font></a></li>");
document.write("</ul></div>");
