document.write("<div id=सर्वार्थसिद्धि class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿देवाश्चतुर्णिकाया:॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkGreen>आदितस्त्रिषु पीतान्तलेश्या:॥२॥</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>दशाष्ट-पञ्च-द्वादश-विकल्पा कल्पोपपन्न पर्यन्ता:॥३॥</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>इंद्र-सामानिक-त्रायस्ंित्रश-पारिषदात्मरक्ष-लोकपालानीक-प्रकीर्णकाभियोग्यकिल्विषिकाश्चैकश:॥४॥</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>त्रायिंस्त्रश-लोकपाल-वज्र्या व्यंतरज्योतिष्का:॥५॥</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>पूर्वयोद्र्वीन्द्रा:॥६॥</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>काय-प्रवीचारा आ ऐशानात्॥७॥</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>शेषा: स्पर्श-रूप-शब्द-मन: प्रवीचारा:॥८॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>परेऽप्रवीचारा:॥९॥</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkGreen>भवन-वासिनोऽसुरनाग-विद्युत्सुपर्णाग्निवातस्तनितोदधि-द्वीप-दिक्कुमारा:॥१०॥</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkBlue>व्यन्तरा: किन्नर-विंपुरुष-महोरग-गन्धर्व-यक्ष-राक्षस-भूत-पिशाचा:॥११॥</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkGreen>ज्योतिष्का: सूर्याचन्द्रमसौ ग्रह-नक्षत्र-प्रकीर्णक-तारकाश्च॥१२॥</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkBlue>मेरु-प्रदक्षिणा नित्यगतयो नृलोके॥१३॥</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkGreen>तत्कृत: काल विभाग:॥१४॥</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkBlue>बहिरवस्थिता:॥१५॥</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkGreen>वैमानिका:॥१६॥</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkBlue>कल्पोपपन्ना: कल्पातीताश्च॥१७॥</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkGreen>उपर्युपरि॥१८॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>सौधर्मेशान-सानत्कुमार-माहेन्द्र-ब्रह्म-ब्रह्मोत्तर-लान्तव-कापिष्ट-शुक्र-महाशुक्र-शतार-सहस्रारेष्वानतप्राणत-योरारणाच्युतयोर्नवसु गै्रवेयकेषु विजय-वैजयन्त जयन्तापराजितेषु सर्वार्थ-सिद्धौ च॥१९॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>स्थिति-प्रभाव-सुख-द्युति-लेश्याविशुद्धीन्द्रियावधि-विषय-तोऽधिका:॥२०॥</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkBlue>गति-शरीर-परिग्रहाभिमानतो हीना:॥२१॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>पीत-पद्म-शुक्ल-लेश्या द्वि-त्रि-शेषेषु॥२२॥</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkBlue>प्राग्ग्रैवेयकेभ्य: कल्पा:॥२३॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>ब्रह्म-लोकालया लौकान्तिका:॥२४॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>सारस्वतादित्य वन्ह्यरुण-गर्दतोय-तुषिताव्या-बाधारिष्टाश्च॥२५॥</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkGreen>विजयादिषु द्वि-चरमा:॥२६॥</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkBlue>औपपादिक-मनुष्येभ्य: शेषास्तिर्यग्योनय:॥२७॥</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkGreen>स्थितिरसुर-नाग-सुपर्ण-द्वीपशेषाणां-सागरोपम-त्रिपल्योपमाद्र्धहीन-मिता:॥२८॥</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkBlue>सौधर्मेशानयो: सागरोपमेऽधिके॥२९॥</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkGreen>सानत्कुमार-माहेन्द्रयो: सप्त॥३०॥</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkBlue>त्रिसप्त-नवैकादश-त्रयोदश-पञ्चदशभिरधिकानि तु॥३१॥</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkGreen>आरणाच्युता-दूध्र्वमेवैकेन नवसु ग्रैवेयकेषु विजयादिषु सर्वार्थसिद्धौ च॥३२॥</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkBlue>अपरा पल्योपममधिकम्॥३३॥</font></font></a></li>");
document.write("        <li><a href='34.html'><font size=4><font color=darkPurple><b>34</b></font> - <font color=darkGreen>परत: परत: पूर्वा पूर्वाऽनन्तरा॥३४॥</font></font></a></li>");
document.write("        <li><a href='35.html'><font size=4><font color=darkPurple><b>35</b></font> - <font color=darkBlue>नारकाणां च द्वितीयादिषु॥३५॥</font></font></a></li>");
document.write("        <li><a href='36.html'><font size=4><font color=darkPurple><b>36</b></font> - <font color=darkGreen>दश-वर्षसहस्राणि प्रथमायाम्॥३६॥</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4><font color=darkPurple><b>37</b></font> - <font color=darkBlue>भवनेषु च॥३७॥</font></font></a></li>");
document.write("        <li><a href='38.html'><font size=4><font color=darkPurple><b>38</b></font> - <font color=darkGreen>व्यन्तराणां च॥३८॥</font></font></a></li>");
document.write("        <li><a href='39.html'><font size=4><font color=darkPurple><b>39</b></font> - <font color=darkBlue>परा पल्योपममधिकम्॥३९॥</font></font></a></li>");
document.write("        <li><a href='40.html'><font size=4><font color=darkPurple><b>40</b></font> - <font color=darkGreen>ज्योतिष्काणां च॥४०॥</font></font></a></li>");
document.write("        <li><a href='41.html'><font size=4><font color=darkPurple><b>41</b></font> - <font color=darkBlue>तदष्टभागोऽपरा॥४१॥</font></font></a></li>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkGreen>लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम्॥४२॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=राजवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkBlue>लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम्॥४२॥</font></font></a></li>");
document.write("</ul></div>");
