document.write("<div id=सर्वार्थसिद्धि class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkBlue>एकप्रदेशादिषु भाज्य: पुद्गलानाम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkGreen>असंख्येय-भागादिषु जीवानाम्॥१५॥</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkBlue>प्रदेश-संहार-विसर्पाभ्यां प्रदीपवत्॥१६॥</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkGreen>गति-स्थित्युपग्रहौ धर्माधर्मयोरुपकार:॥१७॥</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkBlue>आकाशस्या-वगाह:॥१८॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkGreen>शरीरवाङ्मन:-प्राणापाना पुद्गलानाम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkBlue>सुख-दु:ख-जीवितमरणोपग्रहाश्च॥२०॥</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkGreen>परस्परोपग्रहो जीवानाम्॥२१॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkBlue>वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य॥२२॥</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkGreen>स्पर्श-रस-गंध-वर्णवन्त: पुद्गला:॥२३॥</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkBlue>शब्द-बंध-सौक्ष्म्य-स्थौल्य-संस्थान-भेद-तमश्छायातपोद्योतवन्तश्च॥२४॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkGreen>अणव: स्कन्धाश्च॥२५॥</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkBlue>भेद-संघातेभ्य उत्पद्यन्ते॥२६॥</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkGreen>भेदादणु:॥२७॥</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkBlue>भेद-संघाताभ्यां चाक्षुष:॥२८॥</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkGreen>सद् द्रव्य-लक्षणम्॥२९॥</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkBlue>उत्पाद-व्यय-ध्रौव्य-युत्तं सत्॥३०॥</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkGreen>तद्भावाव्ययं नित्यम्॥३१॥</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkBlue>अर्पितानर्पितसिद्धे:॥३२॥</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkGreen>स्निग्ध-रूक्षत्वाद्बंध:॥३३॥</font></font></a></li>");
document.write("        <li><a href='34.html'><font size=4><font color=darkPurple><b>34</b></font> - <font color=darkBlue>न जघन्य-गुणानाम्॥३४॥</font></font></a></li>");
document.write("        <li><a href='35.html'><font size=4><font color=darkPurple><b>35</b></font> - <font color=darkGreen>गुणसाम्ये सदृशानाम्॥३५॥</font></font></a></li>");
document.write("        <li><a href='36.html'><font size=4><font color=darkPurple><b>36</b></font> - <font color=darkBlue>द्व्यधिकादि गुणानां तु॥३६॥</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4><font color=darkPurple><b>37</b></font> - <font color=darkGreen>बन्धेऽधिकौ पारिणामिकौ च॥३७॥</font></font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("        <li><a href='38.html'><font size=4><font color=darkPurple><b>38</b></font> - <font color=darkGreen>गुण-पर्ययवद् द्रव्यम्॥३८॥</font></font></a></li>");
document.write("        <li><a href='39.html'><font size=4><font color=darkPurple><b>39</b></font> - <font color=darkBlue>कालश्च॥३९॥</font></font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("        <li><a href='40.html'><font size=4><font color=darkPurple><b>40</b></font> - <font color=darkBlue>सोऽनन्तसमय:॥४०॥</font></font></a></li>");
document.write("        <li><a href='41.html'><font size=4><font color=darkPurple><b>41</b></font> - <font color=darkGreen>द्रव्याश्रया निर्गुणा गुणा:॥४१॥</font></font></a></li>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkBlue>तद्भाव: परिणाम:॥४२॥</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=राजवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkGreen>﻿अजीव-काया-धर्माधर्माकाश-पुद्गला:॥१॥</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkBlue>द्रव्याणि॥२॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkGreen>आकाशस्यानन्ता:॥९॥</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>शरीरवाङ्मन:-प्राणापाना पुद्गलानाम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य॥२२॥</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>अणव: स्कन्धाश्च॥२५॥</font></font></a></li>");
document.write("</ul></div>");
